# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:
email:
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/govlab-blog" # the subpath of your site, e.g. /blog
url: "https://govlab.github.io/govlab-docs-template" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
markdown: kramdown

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

# Folder Structure
source: ./source
# sass_dir: source/css

collections:
- docs

contentful:
  spaces:
    - blog:
        space: 6guumcycw6jo
        access_token: 99f3b3a28764c9bec785953db09c604b61518fc0dc6907038b5866ea79d6e5e1
        base_path: source
        all_entries: true
        cda_query:
          include: 10
          limit: 1000


page_gen:
  - data: contentful.spaces.blog.blogPost
    template: post
    name: title
    dir: blog
    extension: html
  - data: contentful.spaces.blog.digestPost
    template: post
    name: title
    dir: digest
    extension: html

# page_gen:
#   - data: 'portfolio'
#     template: 'project-template'
#     name: 'title'
#     dir: '/'
